/**
 * Social Graph API
 * Pho Networks REST API
 *
 * OpenAPI spec version: 1.1.1
 * Contact: emre@phonetworks.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/*
 * SWGInline_response_200_3_in.h
 * 
 * 
 */

#ifndef SWGInline_response_200_3_in_H_
#define SWGInline_response_200_3_in_H_

#include <QJsonObject>


#include "SWGNodeEdge.h"

#include "SWGObject.h"


namespace Swagger {

class SWGInline_response_200_3_in: public SWGObject {
public:
    SWGInline_response_200_3_in();
    SWGInline_response_200_3_in(QString* json);
    virtual ~SWGInline_response_200_3_in();
    void init();
    void cleanup();

    QString asJson ();
    QJsonObject* asJsonObject();
    void fromJsonObject(QJsonObject &json);
    SWGInline_response_200_3_in* fromJson(QString &jsonString);

    SWGNodeEdge* get5f9e769ff6fe4cee02b3b4547200db6b();
    void set5f9e769ff6fe4cee02b3b4547200db6b(SWGNodeEdge* _5f9e769ff6fe4cee02b3b4547200db6b);


private:
    SWGNodeEdge* _5f9e769ff6fe4cee02b3b4547200db6b;
};

} /* namespace Swagger */

#endif /* SWGInline_response_200_3_in_H_ */
