/**
 * Social Graph API
 * Pho Networks REST API
 *
 * OpenAPI spec version: 1.1.1
 * Contact: emre@phonetworks.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


#include "SWGInline_response_200_4.h"

#include "SWGHelpers.h"

#include <QJsonDocument>
#include <QJsonArray>
#include <QObject>
#include <QDebug>

namespace Swagger {


SWGInline_response_200_4::SWGInline_response_200_4(QString* json) {
    init();
    this->fromJson(*json);
}

SWGInline_response_200_4::SWGInline_response_200_4() {
    init();
}

SWGInline_response_200_4::~SWGInline_response_200_4() {
    this->cleanup();
}

void
SWGInline_response_200_4::init() {
    success = false;
}

void
SWGInline_response_200_4::cleanup() {
    
}

SWGInline_response_200_4*
SWGInline_response_200_4::fromJson(QString &json) {
    QByteArray array (json.toStdString().c_str());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
    return this;
}

void
SWGInline_response_200_4::fromJsonObject(QJsonObject &pJson) {
    ::Swagger::setValue(&success, pJson["success"], "bool", "");
}

QString
SWGInline_response_200_4::asJson ()
{
    QJsonObject* obj = this->asJsonObject();

    QJsonDocument doc(*obj);
    QByteArray bytes = doc.toJson();
    return QString(bytes);
}

QJsonObject*
SWGInline_response_200_4::asJsonObject() {
    QJsonObject* obj = new QJsonObject();
    
    obj->insert("success", QJsonValue(success));

    return obj;
}

bool
SWGInline_response_200_4::getSuccess() {
    return success;
}
void
SWGInline_response_200_4::setSuccess(bool success) {
    this->success = success;
}



} /* namespace Swagger */

