/**
 * Social Graph API
 * Pho Networks REST API
 *
 * OpenAPI spec version: 1.1.1
 * Contact: emre@phonetworks.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


#include "SWGInline_response_200_3_in.h"

#include "SWGHelpers.h"

#include <QJsonDocument>
#include <QJsonArray>
#include <QObject>
#include <QDebug>

namespace Swagger {


SWGInline_response_200_3_in::SWGInline_response_200_3_in(QString* json) {
    init();
    this->fromJson(*json);
}

SWGInline_response_200_3_in::SWGInline_response_200_3_in() {
    init();
}

SWGInline_response_200_3_in::~SWGInline_response_200_3_in() {
    this->cleanup();
}

void
SWGInline_response_200_3_in::init() {
    _5f9e769ff6fe4cee02b3b4547200db6b = new SWGNodeEdge();
}

void
SWGInline_response_200_3_in::cleanup() {
    
    if(_5f9e769ff6fe4cee02b3b4547200db6b != nullptr) {
        delete _5f9e769ff6fe4cee02b3b4547200db6b;
    }
}

SWGInline_response_200_3_in*
SWGInline_response_200_3_in::fromJson(QString &json) {
    QByteArray array (json.toStdString().c_str());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
    return this;
}

void
SWGInline_response_200_3_in::fromJsonObject(QJsonObject &pJson) {
    ::Swagger::setValue(&_5f9e769ff6fe4cee02b3b4547200db6b, pJson["5f9e769ff6fe4cee02b3b4547200db6b"], "SWGNodeEdge", "SWGNodeEdge");
}

QString
SWGInline_response_200_3_in::asJson ()
{
    QJsonObject* obj = this->asJsonObject();

    QJsonDocument doc(*obj);
    QByteArray bytes = doc.toJson();
    return QString(bytes);
}

QJsonObject*
SWGInline_response_200_3_in::asJsonObject() {
    QJsonObject* obj = new QJsonObject();
    
    toJsonValue(QString("5f9e769ff6fe4cee02b3b4547200db6b"), _5f9e769ff6fe4cee02b3b4547200db6b, obj, QString("SWGNodeEdge"));

    return obj;
}

SWGNodeEdge*
SWGInline_response_200_3_in::get5f9e769ff6fe4cee02b3b4547200db6b() {
    return _5f9e769ff6fe4cee02b3b4547200db6b;
}
void
SWGInline_response_200_3_in::set5f9e769ff6fe4cee02b3b4547200db6b(SWGNodeEdge* _5f9e769ff6fe4cee02b3b4547200db6b) {
    this->_5f9e769ff6fe4cee02b3b4547200db6b = _5f9e769ff6fe4cee02b3b4547200db6b;
}



} /* namespace Swagger */

