/**
 * Social Graph API
 * Pho Networks REST API
 *
 * OpenAPI spec version: 1.1.1
 * Contact: emre@phonetworks.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


#include "SWGNodeEdge.h"

#include "SWGHelpers.h"

#include <QJsonDocument>
#include <QJsonArray>
#include <QObject>
#include <QDebug>

namespace Swagger {


SWGNodeEdge::SWGNodeEdge(QString* json) {
    init();
    this->fromJson(*json);
}

SWGNodeEdge::SWGNodeEdge() {
    init();
}

SWGNodeEdge::~SWGNodeEdge() {
    this->cleanup();
}

void
SWGNodeEdge::init() {
    id = NULL;
    classes = new QList<QString*>();
}

void
SWGNodeEdge::cleanup() {
    
    if(id != nullptr) {
        delete id;
    }

    if(classes != nullptr) {
        QList<QString*>* arr = classes;
        foreach(QString* o, *arr) {
            delete o;
        }
        delete classes;
    }
}

SWGNodeEdge*
SWGNodeEdge::fromJson(QString &json) {
    QByteArray array (json.toStdString().c_str());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
    return this;
}

void
SWGNodeEdge::fromJsonObject(QJsonObject &pJson) {
    ::Swagger::setValue(&id, pJson["id"], "SWGUUID", "SWGUUID");
    
    ::Swagger::setValue(&classes, pJson["classes"], "QList", "QString");
    
}

QString
SWGNodeEdge::asJson ()
{
    QJsonObject* obj = this->asJsonObject();

    QJsonDocument doc(*obj);
    QByteArray bytes = doc.toJson();
    return QString(bytes);
}

QJsonObject*
SWGNodeEdge::asJsonObject() {
    QJsonObject* obj = new QJsonObject();
    
    toJsonValue(QString("id"), id, obj, QString("SWGUUID"));

    QJsonArray classesJsonArray;
    toJsonArray((QList<void*>*)classes, &classesJsonArray, "classes", "QString");
    obj->insert("classes", classesJsonArray);

    return obj;
}

SWGUUID*
SWGNodeEdge::getId() {
    return id;
}
void
SWGNodeEdge::setId(SWGUUID* id) {
    this->id = id;
}

QList<QString*>*
SWGNodeEdge::getClasses() {
    return classes;
}
void
SWGNodeEdge::setClasses(QList<QString*>* classes) {
    this->classes = classes;
}



} /* namespace Swagger */

